name: Build DP
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DP
        uses: actions/checkout@v2
      - name: Compile DP
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Release
        id: upload-release-asset 
      - uses: actions/upload-artifact@v2
        with:
          name: my-release
          path: main.pdf
